// ISO 3166-1 alpha-2 country codes mapped to full country names
// Covers all major music-producing countries
export const COUNTRY_CODE_TO_NAME: Record<string, string[]> = {
  // Africa
  'DZ': ['Algeria'],
  'AO': ['Angola'],
  'BJ': ['Benin'],
  'BW': ['Botswana'],
  'BF': ['Burkina Faso'],
  'BI': ['Burundi'],
  'CM': ['Cameroon'],
  'CV': ['Cape Verde'],
  'CF': ['Central African Republic'],
  'TD': ['Chad'],
  'KM': ['Comoros'],
  'CG': ['Congo', 'Republic of the Congo'],
  'CD': ['Democratic Republic of the Congo', 'DRC', 'Congo-Kinshasa'],
  'CI': ['Ivory Coast', "Côte d'Ivoire"],
  'DJ': ['Djibouti'],
  'EG': ['Egypt'],
  'GQ': ['Equatorial Guinea'],
  'ER': ['Eritrea'],
  'ET': ['Ethiopia'],
  'GA': ['Gabon'],
  'GM': ['Gambia'],
  'GH': ['Ghana'],
  'GN': ['Guinea'],
  'GW': ['Guinea-Bissau'],
  'KE': ['Kenya'],
  'LS': ['Lesotho'],
  'LR': ['Liberia'],
  'LY': ['Libya'],
  'MG': ['Madagascar'],
  'MW': ['Malawi'],
  'ML': ['Mali'],
  'MR': ['Mauritania'],
  'MU': ['Mauritius'],
  'MA': ['Morocco'],
  'MZ': ['Mozambique'],
  'NA': ['Namibia'],
  'NE': ['Niger'],
  'NG': ['Nigeria'],
  'RW': ['Rwanda'],
  'ST': ['São Tomé and Príncipe'],
  'SN': ['Senegal'],
  'SC': ['Seychelles'],
  'SL': ['Sierra Leone'],
  'SO': ['Somalia'],
  'ZA': ['South Africa'],
  'SS': ['South Sudan'],
  'SD': ['Sudan'],
  'SZ': ['Swaziland', 'Eswatini'],
  'TZ': ['Tanzania'],
  'TG': ['Togo'],
  'TN': ['Tunisia'],
  'UG': ['Uganda'],
  'ZM': ['Zambia'],
  'ZW': ['Zimbabwe'],

  // Americas
  'AR': ['Argentina'],
  'BS': ['Bahamas'],
  'BB': ['Barbados'],
  'BZ': ['Belize'],
  'BO': ['Bolivia'],
  'BR': ['Brazil'],
  'CA': ['Canada'],
  'CL': ['Chile'],
  'CO': ['Colombia'],
  'CR': ['Costa Rica'],
  'CU': ['Cuba'],
  'DM': ['Dominica'],
  'DO': ['Dominican Republic'],
  'EC': ['Ecuador'],
  'SV': ['El Salvador'],
  'GT': ['Guatemala'],
  'GY': ['Guyana'],
  'HT': ['Haiti'],
  'HN': ['Honduras'],
  'JM': ['Jamaica'],
  'MX': ['Mexico'],
  'NI': ['Nicaragua'],
  'PA': ['Panama'],
  'PY': ['Paraguay'],
  'PE': ['Peru'],
  'PR': ['Puerto Rico'],
  'SR': ['Suriname'],
  'TT': ['Trinidad and Tobago'],
  'US': ['United States', 'USA', 'United States of America'],
  'UY': ['Uruguay'],
  'VE': ['Venezuela'],

  // Asia
  'AF': ['Afghanistan'],
  'BD': ['Bangladesh'],
  'BT': ['Bhutan'],
  'BN': ['Brunei'],
  'KH': ['Cambodia'],
  'CN': ['China'],
  'IN': ['India'],
  'ID': ['Indonesia'],
  'IR': ['Iran'],
  'IQ': ['Iraq'],
  'IL': ['Israel'],
  'JP': ['Japan'],
  'JO': ['Jordan'],
  'KZ': ['Kazakhstan'],
  'KP': ['North Korea'],
  'KR': ['South Korea', 'Korea'],
  'KW': ['Kuwait'],
  'KG': ['Kyrgyzstan'],
  'LA': ['Laos'],
  'LB': ['Lebanon'],
  'MY': ['Malaysia'],
  'MV': ['Maldives'],
  'MN': ['Mongolia'],
  'MM': ['Myanmar', 'Burma'],
  'NP': ['Nepal'],
  'OM': ['Oman'],
  'PK': ['Pakistan'],
  'PS': ['Palestine'],
  'PH': ['Philippines'],
  'QA': ['Qatar'],
  'SA': ['Saudi Arabia'],
  'SG': ['Singapore'],
  'LK': ['Sri Lanka'],
  'SY': ['Syria'],
  'TW': ['Taiwan'],
  'TJ': ['Tajikistan'],
  'TH': ['Thailand'],
  'TL': ['Timor-Leste', 'East Timor'],
  'TR': ['Turkey'],
  'TM': ['Turkmenistan'],
  'AE': ['United Arab Emirates', 'UAE'],
  'UZ': ['Uzbekistan'],
  'VN': ['Vietnam'],
  'YE': ['Yemen'],

  // Europe
  'AL': ['Albania'],
  'AD': ['Andorra'],
  'AM': ['Armenia'],
  'AT': ['Austria'],
  'AZ': ['Azerbaijan'],
  'BY': ['Belarus'],
  'BE': ['Belgium'],
  'BA': ['Bosnia and Herzegovina'],
  'BG': ['Bulgaria'],
  'HR': ['Croatia'],
  'CY': ['Cyprus'],
  'CZ': ['Czech Republic', 'Czechia'],
  'DK': ['Denmark'],
  'EE': ['Estonia'],
  'FI': ['Finland'],
  'FR': ['France'],
  'GE': ['Georgia'],
  'DE': ['Germany'],
  'GR': ['Greece'],
  'HU': ['Hungary'],
  'IS': ['Iceland'],
  'IE': ['Ireland'],
  'IT': ['Italy'],
  'XK': ['Kosovo'],
  'LV': ['Latvia'],
  'LI': ['Liechtenstein'],
  'LT': ['Lithuania'],
  'LU': ['Luxembourg'],
  'MK': ['North Macedonia', 'Macedonia'],
  'MT': ['Malta'],
  'MD': ['Moldova'],
  'MC': ['Monaco'],
  'ME': ['Montenegro'],
  'NL': ['Netherlands', 'Holland'],
  'NO': ['Norway'],
  'PL': ['Poland'],
  'PT': ['Portugal'],
  'RO': ['Romania'],
  'RU': ['Russia', 'Russian Federation'],
  'SM': ['San Marino'],
  'RS': ['Serbia'],
  'SK': ['Slovakia'],
  'SI': ['Slovenia'],
  'ES': ['Spain'],
  'SE': ['Sweden'],
  'CH': ['Switzerland'],
  'UA': ['Ukraine'],
  'GB': ['United Kingdom', 'UK', 'Great Britain', 'Britain'],
  'VA': ['Vatican City'],

  // Oceania
  'AU': ['Australia'],
  'FJ': ['Fiji'],
  'KI': ['Kiribati'],
  'MH': ['Marshall Islands'],
  'FM': ['Micronesia'],
  'NR': ['Nauru'],
  'NZ': ['New Zealand'],
  'PW': ['Palau'],
  'PG': ['Papua New Guinea'],
  'WS': ['Samoa'],
  'SB': ['Solomon Islands'],
  'TO': ['Tonga'],
  'TV': ['Tuvalu'],
  'VU': ['Vanuatu'],

  // Middle East (additional)
  'BH': ['Bahrain'],
}

// Helper function to check if a country code matches any of the target countries
export function countryCodeMatchesAny(
  countryCode: string | undefined,
  targetCountries: string[]
): boolean {
  if (!countryCode) return false
  
  const countryNames = COUNTRY_CODE_TO_NAME[countryCode.toUpperCase()] || []
  
  return targetCountries.some(target => 
    countryNames.some(name => 
      name.toLowerCase() === target.toLowerCase()
    )
  )
}